// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetActionsJobsJob {
    completedAt?: string;
    conclusion?: string;
    createdAt?: string;
    headBranch?: string;
    headSha?: string;
    htmlUrl?: string;
    id?: number;
    labels?: string[];
    name?: string;
    runAttempt?: number;
    runId?: number;
    runUrl?: string;
    runnerId?: number;
    runnerName?: string;
    startedAt?: string;
    status?: string;
    steps?: outputs.GetActionsJobsJobStep[];
    url?: string;
}

export interface GetActionsJobsJobStep {
    completedAt?: string;
    conclusion?: string;
    name?: string;
    number?: number;
    startedAt?: string;
    status?: string;
}

export interface GetActionsRunnersRunner {
    busy?: boolean;
    disabled?: boolean;
    ephemeral?: boolean;
    id?: number;
    labels?: outputs.GetActionsRunnersRunnerLabel[];
    name?: string;
    status?: string;
}

export interface GetActionsRunnersRunnerLabel {
    id?: number;
    name?: string;
    type?: string;
}

export interface GetActionsRunsWorkflowRun {
    completedAt?: string;
    conclusion?: string;
    displayTitle?: string;
    event?: string;
    headBranch?: string;
    headSha?: string;
    htmlUrl?: string;
    id?: number;
    path?: string;
    runAttempt?: number;
    runNumber?: number;
    startedAt?: string;
    status?: string;
    url?: string;
}

export interface GetIssueAttachmentsAttachment {
    createdAt?: string;
    downloadCount?: number;
    downloadUrl?: string;
    id?: number;
    name?: string;
    size?: number;
    uuid?: string;
}

export interface GetIssueCommentAttachmentsAttachment {
    createdAt?: string;
    downloadCount?: number;
    downloadUrl?: string;
    id?: number;
    name?: string;
    size?: number;
    uuid?: string;
}

export interface GetPackageVersionsVersion {
    createdAt?: string;
    creator?: string;
    htmlUrl?: string;
    id?: number;
    name?: string;
    owner?: string;
    repository?: string;
    type?: string;
    version?: string;
}

export interface GetPullRequestByBaseHeadPullRequest {
    baseRef?: string;
    body?: string;
    closedAt?: string;
    comments?: number;
    createdAt?: string;
    diffUrl?: string;
    draft?: boolean;
    hasMerged?: boolean;
    headRef?: string;
    htmlUrl?: string;
    id?: number;
    index?: number;
    isLocked?: boolean;
    mergeBase?: string;
    mergeCommit?: string;
    mergeable?: boolean;
    mergedAt?: string;
    patchUrl?: string;
    state?: string;
    title?: string;
    updatedAt?: string;
}

export interface GetRepositoriesRepository {
    archived?: boolean;
    cloneUrl?: string;
    created?: string;
    defaultBranch?: string;
    description?: string;
    fork?: boolean;
    forks?: number;
    fullName?: string;
    htmlUrl?: string;
    id?: number;
    mirror?: boolean;
    name?: string;
    openIssues?: number;
    private?: boolean;
    size?: number;
    sshUrl?: string;
    stars?: number;
    updated?: string;
    watchers?: number;
    website?: string;
}

export interface GetRepositoryActionsArtifactsArtifact {
    archiveDownloadUrl?: string;
    createdAt?: string;
    expired?: boolean;
    expiresAt?: string;
    id?: number;
    name?: string;
    sizeInBytes?: number;
    updatedAt?: string;
    url?: string;
    workflowRunId?: number;
}

export interface GetRepositoryActionsWorkflowsWorkflow {
    badgeUrl?: string;
    createdAt?: string;
    deletedAt?: string;
    htmlUrl?: string;
    id?: string;
    name?: string;
    path?: string;
    state?: string;
    updatedAt?: string;
    url?: string;
}

export interface GetRepositoryFilesFile {
    content?: string;
    downloadUrl?: string;
    encoding?: string;
    gitUrl?: string;
    htmlUrl?: string;
    lastAuthorDate?: string;
    lastCommitMessage?: string;
    lastCommitSha?: string;
    lastCommitterDate?: string;
    lfsOid?: string;
    lfsSize?: number;
    name?: string;
    path?: string;
    sha?: string;
    size?: number;
    submoduleGitUrl?: string;
    target?: string;
    type?: string;
    url?: string;
}

export interface GetRepositoryIssueConfigContactLink {
    about?: string;
    name?: string;
    url?: string;
}

export interface GetRepositorySubscribersSubscriber {
    avatarUrl?: string;
    email?: string;
    fullName?: string;
    id?: number;
    username?: string;
}

export interface GetTeamMembersMember {
    avatarUrl?: string;
    email?: string;
    fullName?: string;
    id?: number;
    username?: string;
}

export interface GetTeamsTeam {
    canCreateRepos?: boolean;
    description?: string;
    id?: number;
    includeAllRepositories?: boolean;
    name?: string;
    permission?: string;
    units?: string[];
}

