// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getActionsRunnerRegistrationToken(args: GetActionsRunnerRegistrationTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetActionsRunnerRegistrationTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getActionsRunnerRegistrationToken:getActionsRunnerRegistrationToken", {
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRunnerRegistrationToken.
 */
export interface GetActionsRunnerRegistrationTokenArgs {
    id?: string;
    org?: string;
    repository?: string;
    repositoryOwner?: string;
    scope: string;
}

/**
 * A collection of values returned by getActionsRunnerRegistrationToken.
 */
export interface GetActionsRunnerRegistrationTokenResult {
    readonly id: string;
    readonly org?: string;
    readonly repository?: string;
    readonly repositoryOwner?: string;
    readonly scope: string;
    readonly token: string;
}
export function getActionsRunnerRegistrationTokenOutput(args: GetActionsRunnerRegistrationTokenOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetActionsRunnerRegistrationTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getActionsRunnerRegistrationToken:getActionsRunnerRegistrationToken", {
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRunnerRegistrationToken.
 */
export interface GetActionsRunnerRegistrationTokenOutputArgs {
    id?: pulumi.Input<string | undefined>;
    org?: pulumi.Input<string | undefined>;
    repository?: pulumi.Input<string | undefined>;
    repositoryOwner?: pulumi.Input<string | undefined>;
    scope: pulumi.Input<string>;
}
