// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getActionsRuns(args: GetActionsRunsArgs, opts?: pulumi.InvokeOptions): Promise<GetActionsRunsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getActionsRuns:getActionsRuns", {
        "actor": args.actor,
        "branch": args.branch,
        "event": args.event,
        "headSha": args.headSha,
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
        "status": args.status,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRuns.
 */
export interface GetActionsRunsArgs {
    actor?: string;
    branch?: string;
    event?: string;
    headSha?: string;
    id?: string;
    org?: string;
    repository?: string;
    repositoryOwner?: string;
    scope: string;
    status?: string;
}

/**
 * A collection of values returned by getActionsRuns.
 */
export interface GetActionsRunsResult {
    readonly actor?: string;
    readonly branch?: string;
    readonly event?: string;
    readonly headSha?: string;
    readonly id: string;
    readonly org?: string;
    readonly repository?: string;
    readonly repositoryOwner?: string;
    readonly scope: string;
    readonly status?: string;
    readonly totalCount: number;
    readonly workflowRuns: outputs.GetActionsRunsWorkflowRun[];
}
export function getActionsRunsOutput(args: GetActionsRunsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetActionsRunsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getActionsRuns:getActionsRuns", {
        "actor": args.actor,
        "branch": args.branch,
        "event": args.event,
        "headSha": args.headSha,
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
        "status": args.status,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRuns.
 */
export interface GetActionsRunsOutputArgs {
    actor?: pulumi.Input<string | undefined>;
    branch?: pulumi.Input<string | undefined>;
    event?: pulumi.Input<string | undefined>;
    headSha?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    org?: pulumi.Input<string | undefined>;
    repository?: pulumi.Input<string | undefined>;
    repositoryOwner?: pulumi.Input<string | undefined>;
    scope: pulumi.Input<string>;
    status?: pulumi.Input<string | undefined>;
}
