// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getActionsRunners(args: GetActionsRunnersArgs, opts?: pulumi.InvokeOptions): Promise<GetActionsRunnersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getActionsRunners:getActionsRunners", {
        "disabled": args.disabled,
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRunners.
 */
export interface GetActionsRunnersArgs {
    disabled?: boolean;
    id?: string;
    org?: string;
    repository?: string;
    repositoryOwner?: string;
    scope: string;
}

/**
 * A collection of values returned by getActionsRunners.
 */
export interface GetActionsRunnersResult {
    readonly disabled?: boolean;
    readonly id: string;
    readonly org?: string;
    readonly repository?: string;
    readonly repositoryOwner?: string;
    readonly runners: outputs.GetActionsRunnersRunner[];
    readonly scope: string;
    readonly totalCount: number;
}
export function getActionsRunnersOutput(args: GetActionsRunnersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetActionsRunnersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getActionsRunners:getActionsRunners", {
        "disabled": args.disabled,
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsRunners.
 */
export interface GetActionsRunnersOutputArgs {
    disabled?: pulumi.Input<boolean | undefined>;
    id?: pulumi.Input<string | undefined>;
    org?: pulumi.Input<string | undefined>;
    repository?: pulumi.Input<string | undefined>;
    repositoryOwner?: pulumi.Input<string | undefined>;
    scope: pulumi.Input<string>;
}
