// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getActionsJobs(args: GetActionsJobsArgs, opts?: pulumi.InvokeOptions): Promise<GetActionsJobsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getActionsJobs:getActionsJobs", {
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "runId": args.runId,
        "scope": args.scope,
        "status": args.status,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsJobs.
 */
export interface GetActionsJobsArgs {
    id?: string;
    org?: string;
    repository?: string;
    repositoryOwner?: string;
    runId?: number;
    scope: string;
    status?: string;
}

/**
 * A collection of values returned by getActionsJobs.
 */
export interface GetActionsJobsResult {
    readonly id: string;
    readonly jobs: outputs.GetActionsJobsJob[];
    readonly org?: string;
    readonly repository?: string;
    readonly repositoryOwner?: string;
    readonly runId?: number;
    readonly scope: string;
    readonly status?: string;
    readonly totalCount: number;
}
export function getActionsJobsOutput(args: GetActionsJobsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetActionsJobsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getActionsJobs:getActionsJobs", {
        "id": args.id,
        "org": args.org,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "runId": args.runId,
        "scope": args.scope,
        "status": args.status,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getActionsJobs.
 */
export interface GetActionsJobsOutputArgs {
    id?: pulumi.Input<string | undefined>;
    org?: pulumi.Input<string | undefined>;
    repository?: pulumi.Input<string | undefined>;
    repositoryOwner?: pulumi.Input<string | undefined>;
    runId?: pulumi.Input<number | undefined>;
    scope: pulumi.Input<string>;
    status?: pulumi.Input<string | undefined>;
}
