// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIssueAttachments(args: GetIssueAttachmentsArgs, opts?: pulumi.InvokeOptions): Promise<GetIssueAttachmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getIssueAttachments:getIssueAttachments", {
        "id": args.id,
        "issueIndex": args.issueIndex,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueAttachments.
 */
export interface GetIssueAttachmentsArgs {
    id?: string;
    issueIndex: number;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getIssueAttachments.
 */
export interface GetIssueAttachmentsResult {
    readonly attachments: outputs.GetIssueAttachmentsAttachment[];
    readonly id: string;
    readonly issueIndex: number;
    readonly repository: string;
    readonly repositoryOwner: string;
}
export function getIssueAttachmentsOutput(args: GetIssueAttachmentsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIssueAttachmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getIssueAttachments:getIssueAttachments", {
        "id": args.id,
        "issueIndex": args.issueIndex,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueAttachments.
 */
export interface GetIssueAttachmentsOutputArgs {
    id?: pulumi.Input<string | undefined>;
    issueIndex: pulumi.Input<number>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
