// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIssueCommentAttachments(args: GetIssueCommentAttachmentsArgs, opts?: pulumi.InvokeOptions): Promise<GetIssueCommentAttachmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getIssueCommentAttachments:getIssueCommentAttachments", {
        "commentId": args.commentId,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueCommentAttachments.
 */
export interface GetIssueCommentAttachmentsArgs {
    commentId: number;
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getIssueCommentAttachments.
 */
export interface GetIssueCommentAttachmentsResult {
    readonly attachments: outputs.GetIssueCommentAttachmentsAttachment[];
    readonly commentId: number;
    readonly id: string;
    readonly repository: string;
    readonly repositoryOwner: string;
}
export function getIssueCommentAttachmentsOutput(args: GetIssueCommentAttachmentsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIssueCommentAttachmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getIssueCommentAttachments:getIssueCommentAttachments", {
        "commentId": args.commentId,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIssueCommentAttachments.
 */
export interface GetIssueCommentAttachmentsOutputArgs {
    commentId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
