// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPackageVersions(args: GetPackageVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetPackageVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getPackageVersions:getPackageVersions", {
        "id": args.id,
        "name": args.name,
        "owner": args.owner,
        "packageType": args.packageType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPackageVersions.
 */
export interface GetPackageVersionsArgs {
    id?: string;
    name: string;
    owner: string;
    packageType: string;
}

/**
 * A collection of values returned by getPackageVersions.
 */
export interface GetPackageVersionsResult {
    readonly id: string;
    readonly name: string;
    readonly owner: string;
    readonly packageType: string;
    readonly versions: outputs.GetPackageVersionsVersion[];
}
export function getPackageVersionsOutput(args: GetPackageVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPackageVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getPackageVersions:getPackageVersions", {
        "id": args.id,
        "name": args.name,
        "owner": args.owner,
        "packageType": args.packageType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPackageVersions.
 */
export interface GetPackageVersionsOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name: pulumi.Input<string>;
    owner: pulumi.Input<string>;
    packageType: pulumi.Input<string>;
}
