// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPullRequestByBaseHead(args: GetPullRequestByBaseHeadArgs, opts?: pulumi.InvokeOptions): Promise<GetPullRequestByBaseHeadResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getPullRequestByBaseHead:getPullRequestByBaseHead", {
        "baseRef": args.baseRef,
        "headRef": args.headRef,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPullRequestByBaseHead.
 */
export interface GetPullRequestByBaseHeadArgs {
    baseRef: string;
    headRef: string;
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getPullRequestByBaseHead.
 */
export interface GetPullRequestByBaseHeadResult {
    readonly baseRef: string;
    readonly headRef: string;
    readonly id: string;
    readonly pullRequests: outputs.GetPullRequestByBaseHeadPullRequest[];
    readonly repository: string;
    readonly repositoryOwner: string;
}
export function getPullRequestByBaseHeadOutput(args: GetPullRequestByBaseHeadOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPullRequestByBaseHeadResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getPullRequestByBaseHead:getPullRequestByBaseHead", {
        "baseRef": args.baseRef,
        "headRef": args.headRef,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPullRequestByBaseHead.
 */
export interface GetPullRequestByBaseHeadOutputArgs {
    baseRef: pulumi.Input<string>;
    headRef: pulumi.Input<string>;
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
