// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryIssueConfig(args: GetRepositoryIssueConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryIssueConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryIssueConfig:getRepositoryIssueConfig", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryIssueConfig.
 */
export interface GetRepositoryIssueConfigArgs {
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositoryIssueConfig.
 */
export interface GetRepositoryIssueConfigResult {
    readonly blankIssuesEnabled: boolean;
    readonly contactLinks: outputs.GetRepositoryIssueConfigContactLink[];
    readonly id: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly valid: boolean;
    readonly validationMessage: string;
}
export function getRepositoryIssueConfigOutput(args: GetRepositoryIssueConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryIssueConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryIssueConfig:getRepositoryIssueConfig", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryIssueConfig.
 */
export interface GetRepositoryIssueConfigOutputArgs {
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
