// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepositoryFile(args: GetRepositoryFileArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryFile:getRepositoryFile", {
        "branch": args.branch,
        "filePath": args.filePath,
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryFile.
 */
export interface GetRepositoryFileArgs {
    branch?: string;
    filePath: string;
    id?: string;
    name: string;
    username: string;
}

/**
 * A collection of values returned by getRepositoryFile.
 */
export interface GetRepositoryFileResult {
    readonly branch?: string;
    readonly commitMessage: string;
    readonly content: string;
    readonly createdAt: string;
    readonly filePath: string;
    readonly fileSha: string;
    readonly id: string;
    readonly lastCommitSha: string;
    readonly name: string;
    readonly size: number;
    readonly username: string;
}
export function getRepositoryFileOutput(args: GetRepositoryFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryFile:getRepositoryFile", {
        "branch": args.branch,
        "filePath": args.filePath,
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryFile.
 */
export interface GetRepositoryFileOutputArgs {
    branch?: pulumi.Input<string | undefined>;
    filePath: pulumi.Input<string>;
    id?: pulumi.Input<string | undefined>;
    name: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
