// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepositoryLicenses(args: GetRepositoryLicensesArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryLicensesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryLicenses:getRepositoryLicenses", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryLicenses.
 */
export interface GetRepositoryLicensesArgs {
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositoryLicenses.
 */
export interface GetRepositoryLicensesResult {
    readonly id: string;
    readonly licenses: string[];
    readonly repository: string;
    readonly repositoryOwner: string;
}
export function getRepositoryLicensesOutput(args: GetRepositoryLicensesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryLicensesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryLicenses:getRepositoryLicenses", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryLicenses.
 */
export interface GetRepositoryLicensesOutputArgs {
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
