// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepositoryActionsArtifact(args: GetRepositoryActionsArtifactArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryActionsArtifactResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryActionsArtifact:getRepositoryActionsArtifact", {
        "artifactId": args.artifactId,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsArtifact.
 */
export interface GetRepositoryActionsArtifactArgs {
    artifactId: number;
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositoryActionsArtifact.
 */
export interface GetRepositoryActionsArtifactResult {
    readonly archiveDownloadUrl: string;
    readonly artifactId: number;
    readonly createdAt: string;
    readonly expired: boolean;
    readonly expiresAt: string;
    readonly id: string;
    readonly name: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly sizeInBytes: number;
    readonly updatedAt: string;
    readonly url: string;
    readonly workflowRunId: number;
}
export function getRepositoryActionsArtifactOutput(args: GetRepositoryActionsArtifactOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryActionsArtifactResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryActionsArtifact:getRepositoryActionsArtifact", {
        "artifactId": args.artifactId,
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsArtifact.
 */
export interface GetRepositoryActionsArtifactOutputArgs {
    artifactId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
