// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryActionsArtifacts(args: GetRepositoryActionsArtifactsArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryActionsArtifactsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryActionsArtifacts:getRepositoryActionsArtifacts", {
        "id": args.id,
        "name": args.name,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "runId": args.runId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsArtifacts.
 */
export interface GetRepositoryActionsArtifactsArgs {
    id?: string;
    name?: string;
    repository: string;
    repositoryOwner: string;
    runId?: number;
}

/**
 * A collection of values returned by getRepositoryActionsArtifacts.
 */
export interface GetRepositoryActionsArtifactsResult {
    readonly artifacts: outputs.GetRepositoryActionsArtifactsArtifact[];
    readonly id: string;
    readonly name?: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly runId?: number;
    readonly totalCount: number;
}
export function getRepositoryActionsArtifactsOutput(args: GetRepositoryActionsArtifactsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryActionsArtifactsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryActionsArtifacts:getRepositoryActionsArtifacts", {
        "id": args.id,
        "name": args.name,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "runId": args.runId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsArtifacts.
 */
export interface GetRepositoryActionsArtifactsOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
    runId?: pulumi.Input<number | undefined>;
}
