// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositorySubscribers(args: GetRepositorySubscribersArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositorySubscribersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositorySubscribers:getRepositorySubscribers", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositorySubscribers.
 */
export interface GetRepositorySubscribersArgs {
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositorySubscribers.
 */
export interface GetRepositorySubscribersResult {
    readonly id: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly subscribers: outputs.GetRepositorySubscribersSubscriber[];
}
export function getRepositorySubscribersOutput(args: GetRepositorySubscribersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositorySubscribersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositorySubscribers:getRepositorySubscribers", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositorySubscribers.
 */
export interface GetRepositorySubscribersOutputArgs {
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
