// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepositorySigningKey(args: GetRepositorySigningKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositorySigningKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositorySigningKey:getRepositorySigningKey", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositorySigningKey.
 */
export interface GetRepositorySigningKeyArgs {
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositorySigningKey.
 */
export interface GetRepositorySigningKeyResult {
    readonly gpgPublicKey: string;
    readonly id: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly sshPublicKey: string;
}
export function getRepositorySigningKeyOutput(args: GetRepositorySigningKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositorySigningKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositorySigningKey:getRepositorySigningKey", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositorySigningKey.
 */
export interface GetRepositorySigningKeyOutputArgs {
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
