// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryActionsWorkflows(args: GetRepositoryActionsWorkflowsArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryActionsWorkflowsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryActionsWorkflows:getRepositoryActionsWorkflows", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsWorkflows.
 */
export interface GetRepositoryActionsWorkflowsArgs {
    id?: string;
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositoryActionsWorkflows.
 */
export interface GetRepositoryActionsWorkflowsResult {
    readonly id: string;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly totalCount: number;
    readonly workflows: outputs.GetRepositoryActionsWorkflowsWorkflow[];
}
export function getRepositoryActionsWorkflowsOutput(args: GetRepositoryActionsWorkflowsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryActionsWorkflowsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryActionsWorkflows:getRepositoryActionsWorkflows", {
        "id": args.id,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryActionsWorkflows.
 */
export interface GetRepositoryActionsWorkflowsOutputArgs {
    id?: pulumi.Input<string | undefined>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
