// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRepositoryWebhook(args: GetRepositoryWebhookArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryWebhook:getRepositoryWebhook", {
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryWebhook.
 */
export interface GetRepositoryWebhookArgs {
    id: number;
    name: string;
    username: string;
}

/**
 * A collection of values returned by getRepositoryWebhook.
 */
export interface GetRepositoryWebhookResult {
    readonly active: boolean;
    readonly authorizationHeader: string;
    readonly branchFilter: string;
    readonly channel: string;
    readonly color: string;
    readonly config: {[key: string]: string};
    readonly contentType: string;
    readonly createdAt: string;
    readonly events: string[];
    readonly httpMethod: string;
    readonly iconUrl: string;
    readonly id: number;
    readonly name: string;
    readonly secret: string;
    readonly slackUsername: string;
    readonly type: string;
    readonly url: string;
    readonly username: string;
}
export function getRepositoryWebhookOutput(args: GetRepositoryWebhookOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryWebhookResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryWebhook:getRepositoryWebhook", {
        "id": args.id,
        "name": args.name,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryWebhook.
 */
export interface GetRepositoryWebhookOutputArgs {
    id: pulumi.Input<number>;
    name: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
