// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryFiles(args: GetRepositoryFilesArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryFilesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getRepositoryFiles:getRepositoryFiles", {
        "branch": args.branch,
        "id": args.id,
        "paths": args.paths,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryFiles.
 */
export interface GetRepositoryFilesArgs {
    branch?: string;
    id?: string;
    paths: string[];
    repository: string;
    repositoryOwner: string;
}

/**
 * A collection of values returned by getRepositoryFiles.
 */
export interface GetRepositoryFilesResult {
    readonly branch?: string;
    readonly files: outputs.GetRepositoryFilesFile[];
    readonly id: string;
    readonly paths: string[];
    readonly repository: string;
    readonly repositoryOwner: string;
}
export function getRepositoryFilesOutput(args: GetRepositoryFilesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryFilesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getRepositoryFiles:getRepositoryFiles", {
        "branch": args.branch,
        "id": args.id,
        "paths": args.paths,
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryFiles.
 */
export interface GetRepositoryFilesOutputArgs {
    branch?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    paths: pulumi.Input<pulumi.Input<string>[]>;
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
}
