// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTeamMembers(args: GetTeamMembersArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamMembersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getTeamMembers:getTeamMembers", {
        "id": args.id,
        "teamId": args.teamId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeamMembers.
 */
export interface GetTeamMembersArgs {
    id?: string;
    teamId: number;
}

/**
 * A collection of values returned by getTeamMembers.
 */
export interface GetTeamMembersResult {
    readonly id: string;
    readonly members: outputs.GetTeamMembersMember[];
    readonly teamId: number;
}
export function getTeamMembersOutput(args: GetTeamMembersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTeamMembersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getTeamMembers:getTeamMembers", {
        "id": args.id,
        "teamId": args.teamId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeamMembers.
 */
export interface GetTeamMembersOutputArgs {
    id?: pulumi.Input<string | undefined>;
    teamId: pulumi.Input<number>;
}
