// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTeam(args: GetTeamArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getTeam:getTeam", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeam.
 */
export interface GetTeamArgs {
    id: number;
}

/**
 * A collection of values returned by getTeam.
 */
export interface GetTeamResult {
    readonly canCreateRepos: boolean;
    readonly description: string;
    readonly id: number;
    readonly includeAllRepositories: boolean;
    readonly name: string;
    readonly organisation: string;
    readonly permission: string;
    readonly units: string[];
    readonly unitsMap: {[key: string]: string};
}
export function getTeamOutput(args: GetTeamOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTeamResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getTeam:getTeam", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeam.
 */
export interface GetTeamOutputArgs {
    id: pulumi.Input<number>;
}
