// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTeamRepository(args: GetTeamRepositoryArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gitea:index/getTeamRepository:getTeamRepository", {
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "teamId": args.teamId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeamRepository.
 */
export interface GetTeamRepositoryArgs {
    repository: string;
    repositoryOwner: string;
    teamId: number;
}

/**
 * A collection of values returned by getTeamRepository.
 */
export interface GetTeamRepositoryResult {
    readonly defaultBranch: string;
    readonly fullName: string;
    readonly htmlUrl: string;
    readonly id: number;
    readonly private: boolean;
    readonly repository: string;
    readonly repositoryOwner: string;
    readonly teamId: number;
}
export function getTeamRepositoryOutput(args: GetTeamRepositoryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTeamRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gitea:index/getTeamRepository:getTeamRepository", {
        "repository": args.repository,
        "repositoryOwner": args.repositoryOwner,
        "teamId": args.teamId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTeamRepository.
 */
export interface GetTeamRepositoryOutputArgs {
    repository: pulumi.Input<string>;
    repositoryOwner: pulumi.Input<string>;
    teamId: pulumi.Input<number>;
}
