// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IssueCommentAttachment extends pulumi.CustomResource {
    /**
     * Get an existing IssueCommentAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IssueCommentAttachmentState, opts?: pulumi.CustomResourceOptions): IssueCommentAttachment {
        return new IssueCommentAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/issueCommentAttachment:IssueCommentAttachment';

    /**
     * Returns true if the given object is an instance of IssueCommentAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IssueCommentAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IssueCommentAttachment.__pulumiType;
    }

    /**
     * The attachment ID.
     */
    declare public /*out*/ readonly attachmentId: pulumi.Output<number>;
    /**
     * The issue comment ID.
     */
    declare public readonly commentId: pulumi.Output<number>;
    /**
     * The attachment creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The attachment download count.
     */
    declare public /*out*/ readonly downloadCount: pulumi.Output<number>;
    /**
     * The attachment download URL.
     */
    declare public /*out*/ readonly downloadUrl: pulumi.Output<string>;
    declare public readonly issueCommentAttachmentId: pulumi.Output<string>;
    /**
     * The attachment name. Defaults to the source file basename.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * The repository owner.
     */
    declare public readonly repositoryOwner: pulumi.Output<string>;
    /**
     * The attachment size in bytes.
     */
    declare public /*out*/ readonly size: pulumi.Output<number>;
    /**
     * The local source file to upload.
     */
    declare public readonly sourcePath: pulumi.Output<string>;
    /**
     * The attachment UUID.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a IssueCommentAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IssueCommentAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IssueCommentAttachmentArgs | IssueCommentAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IssueCommentAttachmentState | undefined;
            resourceInputs["attachmentId"] = state?.attachmentId;
            resourceInputs["commentId"] = state?.commentId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["downloadCount"] = state?.downloadCount;
            resourceInputs["downloadUrl"] = state?.downloadUrl;
            resourceInputs["issueCommentAttachmentId"] = state?.issueCommentAttachmentId;
            resourceInputs["name"] = state?.name;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["repositoryOwner"] = state?.repositoryOwner;
            resourceInputs["size"] = state?.size;
            resourceInputs["sourcePath"] = state?.sourcePath;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as IssueCommentAttachmentArgs | undefined;
            if (args?.commentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'commentId'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            if (args?.repositoryOwner === undefined && !opts.urn) {
                throw new Error("Missing required property 'repositoryOwner'");
            }
            if (args?.sourcePath === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourcePath'");
            }
            resourceInputs["commentId"] = args?.commentId;
            resourceInputs["issueCommentAttachmentId"] = args?.issueCommentAttachmentId;
            resourceInputs["name"] = args?.name;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["repositoryOwner"] = args?.repositoryOwner;
            resourceInputs["sourcePath"] = args?.sourcePath;
            resourceInputs["attachmentId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["downloadCount"] = undefined /*out*/;
            resourceInputs["downloadUrl"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IssueCommentAttachment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IssueCommentAttachment resources.
 */
export interface IssueCommentAttachmentState {
    /**
     * The attachment ID.
     */
    attachmentId?: pulumi.Input<number | undefined>;
    /**
     * The issue comment ID.
     */
    commentId?: pulumi.Input<number | undefined>;
    /**
     * The attachment creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The attachment download count.
     */
    downloadCount?: pulumi.Input<number | undefined>;
    /**
     * The attachment download URL.
     */
    downloadUrl?: pulumi.Input<string | undefined>;
    issueCommentAttachmentId?: pulumi.Input<string | undefined>;
    /**
     * The attachment name. Defaults to the source file basename.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The repository name.
     */
    repository?: pulumi.Input<string | undefined>;
    /**
     * The repository owner.
     */
    repositoryOwner?: pulumi.Input<string | undefined>;
    /**
     * The attachment size in bytes.
     */
    size?: pulumi.Input<number | undefined>;
    /**
     * The local source file to upload.
     */
    sourcePath?: pulumi.Input<string | undefined>;
    /**
     * The attachment UUID.
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IssueCommentAttachment resource.
 */
export interface IssueCommentAttachmentArgs {
    /**
     * The issue comment ID.
     */
    commentId: pulumi.Input<number>;
    issueCommentAttachmentId?: pulumi.Input<string | undefined>;
    /**
     * The attachment name. Defaults to the source file basename.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The repository name.
     */
    repository: pulumi.Input<string>;
    /**
     * The repository owner.
     */
    repositoryOwner: pulumi.Input<string>;
    /**
     * The local source file to upload.
     */
    sourcePath: pulumi.Input<string>;
}
