// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrgActionsSecret extends pulumi.CustomResource {
    /**
     * Get an existing OrgActionsSecret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgActionsSecretState, opts?: pulumi.CustomResourceOptions): OrgActionsSecret {
        return new OrgActionsSecret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/orgActionsSecret:OrgActionsSecret';

    /**
     * Returns true if the given object is an instance of OrgActionsSecret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgActionsSecret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgActionsSecret.__pulumiType;
    }

    /**
     * The Actions secret creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The Actions secret description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The organisation owning the Actions secret.
     */
    declare public readonly org: pulumi.Output<string>;
    declare public readonly orgActionsSecretId: pulumi.Output<string>;
    /**
     * The Actions secret name.
     */
    declare public readonly secretName: pulumi.Output<string>;
    /**
     * The Actions secret value.
     */
    declare public readonly secretValue: pulumi.Output<string>;

    /**
     * Create a OrgActionsSecret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrgActionsSecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgActionsSecretArgs | OrgActionsSecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgActionsSecretState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["org"] = state?.org;
            resourceInputs["orgActionsSecretId"] = state?.orgActionsSecretId;
            resourceInputs["secretName"] = state?.secretName;
            resourceInputs["secretValue"] = state?.secretValue;
        } else {
            const args = argsOrState as OrgActionsSecretArgs | undefined;
            if (args?.org === undefined && !opts.urn) {
                throw new Error("Missing required property 'org'");
            }
            if (args?.secretName === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretName'");
            }
            if (args?.secretValue === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretValue'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["org"] = args?.org;
            resourceInputs["orgActionsSecretId"] = args?.orgActionsSecretId;
            resourceInputs["secretName"] = args?.secretName;
            resourceInputs["secretValue"] = args?.secretValue ? pulumi.secret(args.secretValue) : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secretValue"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OrgActionsSecret.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrgActionsSecret resources.
 */
export interface OrgActionsSecretState {
    /**
     * The Actions secret creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The Actions secret description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The organisation owning the Actions secret.
     */
    org?: pulumi.Input<string | undefined>;
    orgActionsSecretId?: pulumi.Input<string | undefined>;
    /**
     * The Actions secret name.
     */
    secretName?: pulumi.Input<string | undefined>;
    /**
     * The Actions secret value.
     */
    secretValue?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrgActionsSecret resource.
 */
export interface OrgActionsSecretArgs {
    /**
     * The Actions secret description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The organisation owning the Actions secret.
     */
    org: pulumi.Input<string>;
    orgActionsSecretId?: pulumi.Input<string | undefined>;
    /**
     * The Actions secret name.
     */
    secretName: pulumi.Input<string>;
    /**
     * The Actions secret value.
     */
    secretValue: pulumi.Input<string>;
}
