// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrgActionsVariable extends pulumi.CustomResource {
    /**
     * Get an existing OrgActionsVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgActionsVariableState, opts?: pulumi.CustomResourceOptions): OrgActionsVariable {
        return new OrgActionsVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/orgActionsVariable:OrgActionsVariable';

    /**
     * Returns true if the given object is an instance of OrgActionsVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgActionsVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgActionsVariable.__pulumiType;
    }

    /**
     * The Actions variable description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The organisation owning the Actions variable.
     */
    declare public readonly org: pulumi.Output<string>;
    declare public readonly orgActionsVariableId: pulumi.Output<string>;
    /**
     * The Actions variable value.
     */
    declare public readonly value: pulumi.Output<string>;
    /**
     * The Actions variable name.
     */
    declare public readonly variableName: pulumi.Output<string>;

    /**
     * Create a OrgActionsVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrgActionsVariableArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgActionsVariableArgs | OrgActionsVariableState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgActionsVariableState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["org"] = state?.org;
            resourceInputs["orgActionsVariableId"] = state?.orgActionsVariableId;
            resourceInputs["value"] = state?.value;
            resourceInputs["variableName"] = state?.variableName;
        } else {
            const args = argsOrState as OrgActionsVariableArgs | undefined;
            if (args?.org === undefined && !opts.urn) {
                throw new Error("Missing required property 'org'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            if (args?.variableName === undefined && !opts.urn) {
                throw new Error("Missing required property 'variableName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["org"] = args?.org;
            resourceInputs["orgActionsVariableId"] = args?.orgActionsVariableId;
            resourceInputs["value"] = args?.value;
            resourceInputs["variableName"] = args?.variableName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrgActionsVariable.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrgActionsVariable resources.
 */
export interface OrgActionsVariableState {
    /**
     * The Actions variable description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The organisation owning the Actions variable.
     */
    org?: pulumi.Input<string | undefined>;
    orgActionsVariableId?: pulumi.Input<string | undefined>;
    /**
     * The Actions variable value.
     */
    value?: pulumi.Input<string | undefined>;
    /**
     * The Actions variable name.
     */
    variableName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrgActionsVariable resource.
 */
export interface OrgActionsVariableArgs {
    /**
     * The Actions variable description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The organisation owning the Actions variable.
     */
    org: pulumi.Input<string>;
    orgActionsVariableId?: pulumi.Input<string | undefined>;
    /**
     * The Actions variable value.
     */
    value: pulumi.Input<string>;
    /**
     * The Actions variable name.
     */
    variableName: pulumi.Input<string>;
}
