// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RepositoryBranch extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryBranch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryBranchState, opts?: pulumi.CustomResourceOptions): RepositoryBranch {
        return new RepositoryBranch(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/repositoryBranch:RepositoryBranch';

    /**
     * Returns true if the given object is an instance of RepositoryBranch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryBranch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryBranch.__pulumiType;
    }

    /**
     * The name of the created branch
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the target repository
     */
    declare public readonly repository: pulumi.Output<number>;
    declare public readonly repositoryBranchId: pulumi.Output<string>;

    /**
     * Create a RepositoryBranch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryBranchArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryBranchArgs | RepositoryBranchState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryBranchState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["repositoryBranchId"] = state?.repositoryBranchId;
        } else {
            const args = argsOrState as RepositoryBranchArgs | undefined;
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["repositoryBranchId"] = args?.repositoryBranchId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryBranch.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryBranch resources.
 */
export interface RepositoryBranchState {
    /**
     * The name of the created branch
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the target repository
     */
    repository?: pulumi.Input<number | undefined>;
    repositoryBranchId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RepositoryBranch resource.
 */
export interface RepositoryBranchArgs {
    /**
     * The name of the created branch
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the target repository
     */
    repository: pulumi.Input<number>;
    repositoryBranchId?: pulumi.Input<string | undefined>;
}
