// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RepositoryFile extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryFile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryFileState, opts?: pulumi.CustomResourceOptions): RepositoryFile {
        return new RepositoryFile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/repositoryFile:RepositoryFile';

    /**
     * Returns true if the given object is an instance of RepositoryFile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryFile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryFile.__pulumiType;
    }

    /**
     * The branch to create or modify the file in. If not provided, the default branch will be used
     */
    declare public readonly branch: pulumi.Output<string | undefined>;
    /**
     * The commit message to use when creating or updating the file. If not supplied, a default message will be used
     */
    declare public readonly commitMessage: pulumi.Output<string | undefined>;
    /**
     * The content of the file
     */
    declare public readonly content: pulumi.Output<string>;
    /**
     * The creation date of the file commit
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The encoding of the file content. Currently only 'base64' and 'text' are supported. Defaults to 'text'
     */
    declare public readonly encoding: pulumi.Output<string | undefined>;
    /**
     * The path to the file relative to the root of the repository
     */
    declare public readonly filePath: pulumi.Output<string>;
    /**
     * The SHA of the file
     */
    declare public /*out*/ readonly fileSha: pulumi.Output<string>;
    /**
     * The SHA of the last commit
     */
    declare public /*out*/ readonly lastCommitSha: pulumi.Output<string>;
    /**
     * The Name of the repository
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether to overwrite the file if it already exists. This is only applicable when creating a new file.
     */
    declare public readonly overwrite: pulumi.Output<boolean | undefined>;
    declare public readonly repositoryFileId: pulumi.Output<string>;
    /**
     * The size of the file in bytes
     */
    declare public /*out*/ readonly size: pulumi.Output<number>;
    /**
     * The Owner of the repository
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a RepositoryFile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryFileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryFileArgs | RepositoryFileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryFileState | undefined;
            resourceInputs["branch"] = state?.branch;
            resourceInputs["commitMessage"] = state?.commitMessage;
            resourceInputs["content"] = state?.content;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["encoding"] = state?.encoding;
            resourceInputs["filePath"] = state?.filePath;
            resourceInputs["fileSha"] = state?.fileSha;
            resourceInputs["lastCommitSha"] = state?.lastCommitSha;
            resourceInputs["name"] = state?.name;
            resourceInputs["overwrite"] = state?.overwrite;
            resourceInputs["repositoryFileId"] = state?.repositoryFileId;
            resourceInputs["size"] = state?.size;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as RepositoryFileArgs | undefined;
            if (args?.content === undefined && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if (args?.filePath === undefined && !opts.urn) {
                throw new Error("Missing required property 'filePath'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["branch"] = args?.branch;
            resourceInputs["commitMessage"] = args?.commitMessage;
            resourceInputs["content"] = args?.content;
            resourceInputs["encoding"] = args?.encoding;
            resourceInputs["filePath"] = args?.filePath;
            resourceInputs["name"] = args?.name;
            resourceInputs["overwrite"] = args?.overwrite;
            resourceInputs["repositoryFileId"] = args?.repositoryFileId;
            resourceInputs["username"] = args?.username;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fileSha"] = undefined /*out*/;
            resourceInputs["lastCommitSha"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryFile.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryFile resources.
 */
export interface RepositoryFileState {
    /**
     * The branch to create or modify the file in. If not provided, the default branch will be used
     */
    branch?: pulumi.Input<string | undefined>;
    /**
     * The commit message to use when creating or updating the file. If not supplied, a default message will be used
     */
    commitMessage?: pulumi.Input<string | undefined>;
    /**
     * The content of the file
     */
    content?: pulumi.Input<string | undefined>;
    /**
     * The creation date of the file commit
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The encoding of the file content. Currently only 'base64' and 'text' are supported. Defaults to 'text'
     */
    encoding?: pulumi.Input<string | undefined>;
    /**
     * The path to the file relative to the root of the repository
     */
    filePath?: pulumi.Input<string | undefined>;
    /**
     * The SHA of the file
     */
    fileSha?: pulumi.Input<string | undefined>;
    /**
     * The SHA of the last commit
     */
    lastCommitSha?: pulumi.Input<string | undefined>;
    /**
     * The Name of the repository
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Whether to overwrite the file if it already exists. This is only applicable when creating a new file.
     */
    overwrite?: pulumi.Input<boolean | undefined>;
    repositoryFileId?: pulumi.Input<string | undefined>;
    /**
     * The size of the file in bytes
     */
    size?: pulumi.Input<number | undefined>;
    /**
     * The Owner of the repository
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RepositoryFile resource.
 */
export interface RepositoryFileArgs {
    /**
     * The branch to create or modify the file in. If not provided, the default branch will be used
     */
    branch?: pulumi.Input<string | undefined>;
    /**
     * The commit message to use when creating or updating the file. If not supplied, a default message will be used
     */
    commitMessage?: pulumi.Input<string | undefined>;
    /**
     * The content of the file
     */
    content: pulumi.Input<string>;
    /**
     * The encoding of the file content. Currently only 'base64' and 'text' are supported. Defaults to 'text'
     */
    encoding?: pulumi.Input<string | undefined>;
    /**
     * The path to the file relative to the root of the repository
     */
    filePath: pulumi.Input<string>;
    /**
     * The Name of the repository
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Whether to overwrite the file if it already exists. This is only applicable when creating a new file.
     */
    overwrite?: pulumi.Input<boolean | undefined>;
    repositoryFileId?: pulumi.Input<string | undefined>;
    /**
     * The Owner of the repository
     */
    username: pulumi.Input<string>;
}
