// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RepositoryActionsWorkflowState extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryActionsWorkflowState resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryActionsWorkflowStateState, opts?: pulumi.CustomResourceOptions): RepositoryActionsWorkflowState {
        return new RepositoryActionsWorkflowState(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/repositoryActionsWorkflowState:RepositoryActionsWorkflowState';

    /**
     * Returns true if the given object is an instance of RepositoryActionsWorkflowState.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryActionsWorkflowState {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryActionsWorkflowState.__pulumiType;
    }

    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Whether the workflow is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The workflow display name.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * The workflow file path.
     */
    declare public /*out*/ readonly path: pulumi.Output<string>;
    /**
     * The repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    declare public readonly repositoryActionsWorkflowStateId: pulumi.Output<string>;
    /**
     * The repository owner.
     */
    declare public readonly repositoryOwner: pulumi.Output<string>;
    /**
     * The workflow state returned by Gitea.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The workflow ID or file name.
     */
    declare public readonly workflowId: pulumi.Output<string>;

    /**
     * Create a RepositoryActionsWorkflowState resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryActionsWorkflowStateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryActionsWorkflowStateArgs | RepositoryActionsWorkflowStateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryActionsWorkflowStateState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["path"] = state?.path;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["repositoryActionsWorkflowStateId"] = state?.repositoryActionsWorkflowStateId;
            resourceInputs["repositoryOwner"] = state?.repositoryOwner;
            resourceInputs["state"] = state?.state;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["workflowId"] = state?.workflowId;
        } else {
            const args = argsOrState as RepositoryActionsWorkflowStateArgs | undefined;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            if (args?.repositoryOwner === undefined && !opts.urn) {
                throw new Error("Missing required property 'repositoryOwner'");
            }
            if (args?.workflowId === undefined && !opts.urn) {
                throw new Error("Missing required property 'workflowId'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["repositoryActionsWorkflowStateId"] = args?.repositoryActionsWorkflowStateId;
            resourceInputs["repositoryOwner"] = args?.repositoryOwner;
            resourceInputs["workflowId"] = args?.workflowId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["path"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryActionsWorkflowState.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryActionsWorkflowState resources.
 */
export interface RepositoryActionsWorkflowStateState {
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Whether the workflow is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The workflow display name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The workflow file path.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * The repository name.
     */
    repository?: pulumi.Input<string | undefined>;
    repositoryActionsWorkflowStateId?: pulumi.Input<string | undefined>;
    /**
     * The repository owner.
     */
    repositoryOwner?: pulumi.Input<string | undefined>;
    /**
     * The workflow state returned by Gitea.
     */
    state?: pulumi.Input<string | undefined>;
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * The workflow ID or file name.
     */
    workflowId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RepositoryActionsWorkflowState resource.
 */
export interface RepositoryActionsWorkflowStateArgs {
    /**
     * Whether the workflow is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The repository name.
     */
    repository: pulumi.Input<string>;
    repositoryActionsWorkflowStateId?: pulumi.Input<string | undefined>;
    /**
     * The repository owner.
     */
    repositoryOwner: pulumi.Input<string>;
    /**
     * The workflow ID or file name.
     */
    workflowId: pulumi.Input<string>;
}
