// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Team extends pulumi.CustomResource {
    /**
     * Get an existing Team resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamState, opts?: pulumi.CustomResourceOptions): Team {
        return new Team(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/team:Team';

    /**
     * Returns true if the given object is an instance of Team.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Team {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Team.__pulumiType;
    }

    /**
     * Flag if the Teams members should be able to create Rpositories in the Organisation
     */
    declare public readonly canCreateRepos: pulumi.Output<boolean | undefined>;
    /**
     * Description of the Team
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Flag if the Teams members should have access to all Repositories in the Organisation
     */
    declare public readonly includeAllRepositories: pulumi.Output<boolean | undefined>;
    /**
     * Name of the Team
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The organisation which this Team is part of.
     */
    declare public readonly organisation: pulumi.Output<string>;
    /**
     * Permissions associated with this Team
     * Can be <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`read`" pulumi-lang-dotnet="`Read`" pulumi-lang-go="`read`" pulumi-lang-python="`read`" pulumi-lang-yaml="`read`" pulumi-lang-java="`read`" pulumi-lang-hcl="`read`">`read`</span>, <span pulumi-lang-nodejs="`write`" pulumi-lang-dotnet="`Write`" pulumi-lang-go="`write`" pulumi-lang-python="`write`" pulumi-lang-yaml="`write`" pulumi-lang-java="`write`" pulumi-lang-hcl="`write`">`write`</span>, <span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`">`admin`</span> or <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>
     */
    declare public readonly permission: pulumi.Output<string | undefined>;
    /**
     * List of Repositories that should be part of this team
     */
    declare public readonly repositories: pulumi.Output<string[]>;
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * List of types of Repositories that should be allowed to be created from Team members.
     * Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects`, `repo.ext_wiki`, `repo.actions` and/or `repo.packages`
     */
    declare public readonly units: pulumi.Output<string | undefined>;
    /**
     * Map of repository units to their permissions
     */
    declare public readonly unitsMap: pulumi.Output<{[key: string]: string}>;

    /**
     * Create a Team resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamArgs | TeamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeamState | undefined;
            resourceInputs["canCreateRepos"] = state?.canCreateRepos;
            resourceInputs["description"] = state?.description;
            resourceInputs["includeAllRepositories"] = state?.includeAllRepositories;
            resourceInputs["name"] = state?.name;
            resourceInputs["organisation"] = state?.organisation;
            resourceInputs["permission"] = state?.permission;
            resourceInputs["repositories"] = state?.repositories;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["units"] = state?.units;
            resourceInputs["unitsMap"] = state?.unitsMap;
        } else {
            const args = argsOrState as TeamArgs | undefined;
            if (args?.organisation === undefined && !opts.urn) {
                throw new Error("Missing required property 'organisation'");
            }
            resourceInputs["canCreateRepos"] = args?.canCreateRepos;
            resourceInputs["description"] = args?.description;
            resourceInputs["includeAllRepositories"] = args?.includeAllRepositories;
            resourceInputs["name"] = args?.name;
            resourceInputs["organisation"] = args?.organisation;
            resourceInputs["permission"] = args?.permission;
            resourceInputs["repositories"] = args?.repositories;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["units"] = args?.units;
            resourceInputs["unitsMap"] = args?.unitsMap;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Team.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Team resources.
 */
export interface TeamState {
    /**
     * Flag if the Teams members should be able to create Rpositories in the Organisation
     */
    canCreateRepos?: pulumi.Input<boolean | undefined>;
    /**
     * Description of the Team
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Flag if the Teams members should have access to all Repositories in the Organisation
     */
    includeAllRepositories?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the Team
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organisation which this Team is part of.
     */
    organisation?: pulumi.Input<string | undefined>;
    /**
     * Permissions associated with this Team
     * Can be <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`read`" pulumi-lang-dotnet="`Read`" pulumi-lang-go="`read`" pulumi-lang-python="`read`" pulumi-lang-yaml="`read`" pulumi-lang-java="`read`" pulumi-lang-hcl="`read`">`read`</span>, <span pulumi-lang-nodejs="`write`" pulumi-lang-dotnet="`Write`" pulumi-lang-go="`write`" pulumi-lang-python="`write`" pulumi-lang-yaml="`write`" pulumi-lang-java="`write`" pulumi-lang-hcl="`write`">`write`</span>, <span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`">`admin`</span> or <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>
     */
    permission?: pulumi.Input<string | undefined>;
    /**
     * List of Repositories that should be part of this team
     */
    repositories?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    teamId?: pulumi.Input<string | undefined>;
    /**
     * List of types of Repositories that should be allowed to be created from Team members.
     * Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects`, `repo.ext_wiki`, `repo.actions` and/or `repo.packages`
     */
    units?: pulumi.Input<string | undefined>;
    /**
     * Map of repository units to their permissions
     */
    unitsMap?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}

/**
 * The set of arguments for constructing a Team resource.
 */
export interface TeamArgs {
    /**
     * Flag if the Teams members should be able to create Rpositories in the Organisation
     */
    canCreateRepos?: pulumi.Input<boolean | undefined>;
    /**
     * Description of the Team
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Flag if the Teams members should have access to all Repositories in the Organisation
     */
    includeAllRepositories?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the Team
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The organisation which this Team is part of.
     */
    organisation: pulumi.Input<string>;
    /**
     * Permissions associated with this Team
     * Can be <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`read`" pulumi-lang-dotnet="`Read`" pulumi-lang-go="`read`" pulumi-lang-python="`read`" pulumi-lang-yaml="`read`" pulumi-lang-java="`read`" pulumi-lang-hcl="`read`">`read`</span>, <span pulumi-lang-nodejs="`write`" pulumi-lang-dotnet="`Write`" pulumi-lang-go="`write`" pulumi-lang-python="`write`" pulumi-lang-yaml="`write`" pulumi-lang-java="`write`" pulumi-lang-hcl="`write`">`write`</span>, <span pulumi-lang-nodejs="`admin`" pulumi-lang-dotnet="`Admin`" pulumi-lang-go="`admin`" pulumi-lang-python="`admin`" pulumi-lang-yaml="`admin`" pulumi-lang-java="`admin`" pulumi-lang-hcl="`admin`">`admin`</span> or <span pulumi-lang-nodejs="`owner`" pulumi-lang-dotnet="`Owner`" pulumi-lang-go="`owner`" pulumi-lang-python="`owner`" pulumi-lang-yaml="`owner`" pulumi-lang-java="`owner`" pulumi-lang-hcl="`owner`">`owner`</span>
     */
    permission?: pulumi.Input<string | undefined>;
    /**
     * List of Repositories that should be part of this team
     */
    repositories?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    teamId?: pulumi.Input<string | undefined>;
    /**
     * List of types of Repositories that should be allowed to be created from Team members.
     * Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects`, `repo.ext_wiki`, `repo.actions` and/or `repo.packages`
     */
    units?: pulumi.Input<string | undefined>;
    /**
     * Map of repository units to their permissions
     */
    unitsMap?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
