// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Flag if this user should be active or not
     */
    declare public readonly active: pulumi.Output<boolean | undefined>;
    /**
     * Flag if this user should be an administrator or not
     */
    declare public readonly admin: pulumi.Output<boolean | undefined>;
    declare public readonly allowCreateOrganization: pulumi.Output<boolean | undefined>;
    declare public readonly allowGitHook: pulumi.Output<boolean | undefined>;
    declare public readonly allowImportLocal: pulumi.Output<boolean | undefined>;
    /**
     * A description of the user
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * E-Mail Address of the user
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Flag if the user defined password should be overwritten or not
     */
    declare public readonly forcePasswordChange: pulumi.Output<boolean | undefined>;
    /**
     * Full name of the user
     */
    declare public readonly fullName: pulumi.Output<string>;
    declare public readonly location: pulumi.Output<string | undefined>;
    /**
     * The login name can differ from the username
     */
    declare public readonly loginName: pulumi.Output<string>;
    declare public readonly maxRepoCreation: pulumi.Output<number | undefined>;
    /**
     * Flag if the user should change the password after first login
     */
    declare public readonly mustChangePassword: pulumi.Output<boolean | undefined>;
    /**
     * Password to be set for the user
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * Flag if the user should not be allowed to log in (bot user)
     */
    declare public readonly prohibitLogin: pulumi.Output<boolean | undefined>;
    declare public readonly restricted: pulumi.Output<boolean | undefined>;
    /**
     * Flag to send a notification about the user creation to the defined `email`
     */
    declare public readonly sendNotification: pulumi.Output<boolean | undefined>;
    declare public readonly userId: pulumi.Output<string>;
    /**
     * Username of the user to be created
     */
    declare public readonly username: pulumi.Output<string>;
    /**
     * Visibility of the user. Can be `public`, `limited` or `private`
     */
    declare public readonly visibility: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["admin"] = state?.admin;
            resourceInputs["allowCreateOrganization"] = state?.allowCreateOrganization;
            resourceInputs["allowGitHook"] = state?.allowGitHook;
            resourceInputs["allowImportLocal"] = state?.allowImportLocal;
            resourceInputs["description"] = state?.description;
            resourceInputs["email"] = state?.email;
            resourceInputs["forcePasswordChange"] = state?.forcePasswordChange;
            resourceInputs["fullName"] = state?.fullName;
            resourceInputs["location"] = state?.location;
            resourceInputs["loginName"] = state?.loginName;
            resourceInputs["maxRepoCreation"] = state?.maxRepoCreation;
            resourceInputs["mustChangePassword"] = state?.mustChangePassword;
            resourceInputs["password"] = state?.password;
            resourceInputs["prohibitLogin"] = state?.prohibitLogin;
            resourceInputs["restricted"] = state?.restricted;
            resourceInputs["sendNotification"] = state?.sendNotification;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["username"] = state?.username;
            resourceInputs["visibility"] = state?.visibility;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.loginName === undefined && !opts.urn) {
                throw new Error("Missing required property 'loginName'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["admin"] = args?.admin;
            resourceInputs["allowCreateOrganization"] = args?.allowCreateOrganization;
            resourceInputs["allowGitHook"] = args?.allowGitHook;
            resourceInputs["allowImportLocal"] = args?.allowImportLocal;
            resourceInputs["description"] = args?.description;
            resourceInputs["email"] = args?.email;
            resourceInputs["forcePasswordChange"] = args?.forcePasswordChange;
            resourceInputs["fullName"] = args?.fullName;
            resourceInputs["location"] = args?.location;
            resourceInputs["loginName"] = args?.loginName;
            resourceInputs["maxRepoCreation"] = args?.maxRepoCreation;
            resourceInputs["mustChangePassword"] = args?.mustChangePassword;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["prohibitLogin"] = args?.prohibitLogin;
            resourceInputs["restricted"] = args?.restricted;
            resourceInputs["sendNotification"] = args?.sendNotification;
            resourceInputs["userId"] = args?.userId;
            resourceInputs["username"] = args?.username;
            resourceInputs["visibility"] = args?.visibility;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(User.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * Flag if this user should be active or not
     */
    active?: pulumi.Input<boolean>;
    /**
     * Flag if this user should be an administrator or not
     */
    admin?: pulumi.Input<boolean>;
    allowCreateOrganization?: pulumi.Input<boolean>;
    allowGitHook?: pulumi.Input<boolean>;
    allowImportLocal?: pulumi.Input<boolean>;
    /**
     * A description of the user
     */
    description?: pulumi.Input<string>;
    /**
     * E-Mail Address of the user
     */
    email?: pulumi.Input<string>;
    /**
     * Flag if the user defined password should be overwritten or not
     */
    forcePasswordChange?: pulumi.Input<boolean>;
    /**
     * Full name of the user
     */
    fullName?: pulumi.Input<string>;
    location?: pulumi.Input<string>;
    /**
     * The login name can differ from the username
     */
    loginName?: pulumi.Input<string>;
    maxRepoCreation?: pulumi.Input<number>;
    /**
     * Flag if the user should change the password after first login
     */
    mustChangePassword?: pulumi.Input<boolean>;
    /**
     * Password to be set for the user
     */
    password?: pulumi.Input<string>;
    /**
     * Flag if the user should not be allowed to log in (bot user)
     */
    prohibitLogin?: pulumi.Input<boolean>;
    restricted?: pulumi.Input<boolean>;
    /**
     * Flag to send a notification about the user creation to the defined `email`
     */
    sendNotification?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
    /**
     * Username of the user to be created
     */
    username?: pulumi.Input<string>;
    /**
     * Visibility of the user. Can be `public`, `limited` or `private`
     */
    visibility?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Flag if this user should be active or not
     */
    active?: pulumi.Input<boolean>;
    /**
     * Flag if this user should be an administrator or not
     */
    admin?: pulumi.Input<boolean>;
    allowCreateOrganization?: pulumi.Input<boolean>;
    allowGitHook?: pulumi.Input<boolean>;
    allowImportLocal?: pulumi.Input<boolean>;
    /**
     * A description of the user
     */
    description?: pulumi.Input<string>;
    /**
     * E-Mail Address of the user
     */
    email: pulumi.Input<string>;
    /**
     * Flag if the user defined password should be overwritten or not
     */
    forcePasswordChange?: pulumi.Input<boolean>;
    /**
     * Full name of the user
     */
    fullName?: pulumi.Input<string>;
    location?: pulumi.Input<string>;
    /**
     * The login name can differ from the username
     */
    loginName: pulumi.Input<string>;
    maxRepoCreation?: pulumi.Input<number>;
    /**
     * Flag if the user should change the password after first login
     */
    mustChangePassword?: pulumi.Input<boolean>;
    /**
     * Password to be set for the user
     */
    password: pulumi.Input<string>;
    /**
     * Flag if the user should not be allowed to log in (bot user)
     */
    prohibitLogin?: pulumi.Input<boolean>;
    restricted?: pulumi.Input<boolean>;
    /**
     * Flag to send a notification about the user creation to the defined `email`
     */
    sendNotification?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
    /**
     * Username of the user to be created
     */
    username: pulumi.Input<string>;
    /**
     * Visibility of the user. Can be `public`, `limited` or `private`
     */
    visibility?: pulumi.Input<string>;
}
