// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserActionsVariable extends pulumi.CustomResource {
    /**
     * Get an existing UserActionsVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserActionsVariableState, opts?: pulumi.CustomResourceOptions): UserActionsVariable {
        return new UserActionsVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/userActionsVariable:UserActionsVariable';

    /**
     * Returns true if the given object is an instance of UserActionsVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserActionsVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserActionsVariable.__pulumiType;
    }

    /**
     * The user-scoped Actions variable description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly userActionsVariableId: pulumi.Output<string>;
    /**
     * The user-scoped Actions variable value.
     */
    declare public readonly value: pulumi.Output<string>;
    /**
     * The user-scoped Actions variable name.
     */
    declare public readonly variableName: pulumi.Output<string>;

    /**
     * Create a UserActionsVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserActionsVariableArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserActionsVariableArgs | UserActionsVariableState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserActionsVariableState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["userActionsVariableId"] = state?.userActionsVariableId;
            resourceInputs["value"] = state?.value;
            resourceInputs["variableName"] = state?.variableName;
        } else {
            const args = argsOrState as UserActionsVariableArgs | undefined;
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            if (args?.variableName === undefined && !opts.urn) {
                throw new Error("Missing required property 'variableName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["userActionsVariableId"] = args?.userActionsVariableId;
            resourceInputs["value"] = args?.value;
            resourceInputs["variableName"] = args?.variableName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserActionsVariable.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering UserActionsVariable resources.
 */
export interface UserActionsVariableState {
    /**
     * The user-scoped Actions variable description.
     */
    description?: pulumi.Input<string | undefined>;
    userActionsVariableId?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions variable value.
     */
    value?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions variable name.
     */
    variableName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a UserActionsVariable resource.
 */
export interface UserActionsVariableArgs {
    /**
     * The user-scoped Actions variable description.
     */
    description?: pulumi.Input<string | undefined>;
    userActionsVariableId?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions variable value.
     */
    value: pulumi.Input<string>;
    /**
     * The user-scoped Actions variable name.
     */
    variableName: pulumi.Input<string>;
}
