// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserActionsSecret extends pulumi.CustomResource {
    /**
     * Get an existing UserActionsSecret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserActionsSecretState, opts?: pulumi.CustomResourceOptions): UserActionsSecret {
        return new UserActionsSecret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitea:index/userActionsSecret:UserActionsSecret';

    /**
     * Returns true if the given object is an instance of UserActionsSecret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserActionsSecret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserActionsSecret.__pulumiType;
    }

    /**
     * The user-scoped Actions secret description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The user-scoped Actions secret name.
     */
    declare public readonly secretName: pulumi.Output<string>;
    /**
     * The user-scoped Actions secret value.
     */
    declare public readonly secretValue: pulumi.Output<string>;
    declare public readonly userActionsSecretId: pulumi.Output<string>;

    /**
     * Create a UserActionsSecret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserActionsSecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserActionsSecretArgs | UserActionsSecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserActionsSecretState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["secretName"] = state?.secretName;
            resourceInputs["secretValue"] = state?.secretValue;
            resourceInputs["userActionsSecretId"] = state?.userActionsSecretId;
        } else {
            const args = argsOrState as UserActionsSecretArgs | undefined;
            if (args?.secretName === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretName'");
            }
            if (args?.secretValue === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretValue'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["secretName"] = args?.secretName;
            resourceInputs["secretValue"] = args?.secretValue ? pulumi.secret(args.secretValue) : undefined;
            resourceInputs["userActionsSecretId"] = args?.userActionsSecretId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secretValue"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(UserActionsSecret.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering UserActionsSecret resources.
 */
export interface UserActionsSecretState {
    /**
     * The user-scoped Actions secret description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions secret name.
     */
    secretName?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions secret value.
     */
    secretValue?: pulumi.Input<string | undefined>;
    userActionsSecretId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a UserActionsSecret resource.
 */
export interface UserActionsSecretArgs {
    /**
     * The user-scoped Actions secret description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The user-scoped Actions secret name.
     */
    secretName: pulumi.Input<string>;
    /**
     * The user-scoped Actions secret value.
     */
    secretValue: pulumi.Input<string>;
    userActionsSecretId?: pulumi.Input<string | undefined>;
}
